name: Deploy to Dokploy

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      
    - name: Test build
      run: |
        if [ ! -d "dist" ]; then
          echo "Build failed - dist directory not found"
          exit 1
        fi
        
    - name: Deploy to Dokploy
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      env:
        DOKPLOY_TOKEN: ${{ secrets.DOKPLOY_TOKEN }}
        DOKPLOY_URL: ${{ secrets.DOKPLOY_URL }}
      run: |
        # Add your Dokploy deployment script here
        echo "Deploying to Dokploy..."
        # curl -X POST "$DOKPLOY_URL/api/deploy" \
        #   -H "Authorization: Bearer $DOKPLOY_TOKEN" \
        #   -H "Content-Type: application/json" \
        #   -d '{"app": "jobless-journal-frontend", "branch": "main"}'
